#index:
#    path: /
#    controller: App\Controller\BaseController::index

index:
    path: /*
    controller: App\Controller\BaseController::index 

app_home:
    path: /
    controller: App\Controller\HomeController::printHome  

app_top_geschenker:
    path: /topgeschenker
    controller: App\Controller\TopGeschenkController::printNumberList

app_string_reverse:
    path: /string-reverse
    controller: App\Controller\ReverseController::reverseForm

app_quarter_turn:
    path: /kwartslag
    controller: App\Controller\RotatorController::request
